format = 0

[package]
# Must be the URI (without the scheme) of the package.
name = "github.com/luyten-orion/faepkg"

[dependencies.parsetoml]
src        = "github.com/nimparsers/parsetoml"
origin     = "git"
scheme     = "https"
#subdir     = "path/to/pkg/in/repo"
version    = "0.7.2"
# NOTE: `nimble` support is half-baked, it uses a very crappy minimal parser
# and should be replaced with either invoking the actual Skull parser or
# invoking the VM (once it can be sandboxed) as a last resort for
# non-declarative package manifests... Your manifest shouldn't be code though...
foreign-pm = "nimble"

# Proposed syntax
#[features]
#defaults = ["foo", "bar"]

# Accessible to code via `defined(github.com/luyten-orion/faepkg.features.foo)`
#[features.foo.dependencies.alttoml]
#src        = "foo.bar/alttoml"
#origin     = "git"
#scheme     = "https"
#version    = "1.0.0"

#[features.bar.dependencies.richlog]
#src        = "foo.bar/richlog"
#origin     = "git"
#scheme     = "https"
#version    = "1.0.0"
